version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web/
      - static:/static
      - media:/media
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env.dev

  cache:
    image: memcached:alpine

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  postgres_data:
  static:
  media:
