# Generated by Django 4.0.4 on 2022-06-26 12:04

from django.db import migrations, models
import tmc.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostfamily',
            old_name='name',
            new_name='given_name',
        ),
        migrations.AddField(
            model_name='hostfamily',
            name='surname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='secret_id',
            field=models.CharField(default=tmc.models.generate_secret_id, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=254, unique=True, verbose_name='e-mail'),
        ),
    ]
