# Generated by Django 4.0.4 on 2022-06-26 14:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0002_rename_name_hostfamily_given_name_hostfamily_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='passport',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inscription',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('n', 'Non-Binary'), ('x', "Don't know")], max_length=5),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='accomodation_needed',
            field=models.BooleanField(help_text='do you need us to organise accomodation?', verbose_name='accomodation needed'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, help_text='make sure your e-mail is correct, as all communication will be done over e-mail', max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='emergency_contact',
            field=models.CharField(help_text='name of your emergency contact', max_length=120, verbose_name='emergency contact'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='emergency_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='phone number of your emergency contact', max_length=128, region=None, verbose_name='emergency phone'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='emergency_relation',
            field=models.CharField(blank=True, help_text='how are you related to your emergency contact, (family, friends, ...)', max_length=120, verbose_name='emergency relation'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('n', 'Non-Binary'), ('x', "Don't know")], max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='language_of_correspondence',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], max_length=120, verbose_name='language of correspondence'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='notes',
            field=models.TextField(blank=True, help_text='any information that we should know beforhand, not mentioned otherwise in this form', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='please remember to add your country prefix', max_length=128, region=None, verbose_name='phone'),
        ),
    ]
