# Generated by Django 4.0.4 on 2022-06-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0004_alter_inscription_passport_alter_inscription_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='uploader',
        ),
    ]
