# Generated by Django 4.0.4 on 2022-06-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0005_remove_recording_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tmc.inscription'),
            preserve_default=False,
        ),
    ]
