# Generated by Django 4.0.4 on 2022-09-05 16:38

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_auto_20200830_1851'),
        ('tmc', '0006_recording_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostfamily',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='jurymember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jurymember',
            name='last_name',
        ),
        migrations.AddField(
            model_name='correpetitor',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='correpetitor',
            name='email',
            field=models.EmailField(default='test@localhost', error_messages={'unique': 'This email has already been registered.'}, help_text='make sure your e-mail is correct, as all communication will be done over e-mail', max_length=254, unique=True, verbose_name='e-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correpetitor',
            name='given_name',
            field=models.CharField(default='Test', max_length=120, verbose_name='given name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correpetitor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='please remember to add your country prefix', max_length=128, region=None, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correpetitor',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='submitted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correpetitor',
            name='surname',
            field=models.CharField(default='Empty', max_length=120, verbose_name='surname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correpetitor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostfamily',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurymember',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='email',
            field=models.EmailField(default='sandro@sandrocovo.ch', error_messages={'unique': 'This email has already been registered.'}, help_text='make sure your e-mail is correct, as all communication will be done over e-mail', max_length=254, unique=True, verbose_name='e-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurymember',
            name='given_name',
            field=models.CharField(default='Test', max_length=120, verbose_name='given name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurymember',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='please remember to add your country prefix', max_length=128, region=None, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurymember',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='submitted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurymember',
            name='surname',
            field=models.CharField(default='test', max_length=120, verbose_name='surname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurymember',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='double_rooms',
            field=models.PositiveSmallIntegerField(verbose_name='no of double rooms'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, help_text='make sure your e-mail is correct, as all communication will be done over e-mail', max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='given_name',
            field=models.CharField(max_length=120, verbose_name='given name'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='has_own_bathroom',
            field=models.BooleanField(verbose_name='own bathroom'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='has_wifi',
            field=models.BooleanField(verbose_name='wifi'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='languages',
            field=models.ManyToManyField(to='tmc.language', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='pets',
            field=models.CharField(blank=True, help_text='do you have pets and if yes what kind?', max_length=180, verbose_name='pets'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='please remember to add your country prefix', max_length=128, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='practice_allowed',
            field=models.BooleanField(help_text='are contestants allowed to practice?', verbose_name='practice_allowed'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='practice_notes',
            field=models.CharField(blank=True, help_text='are there any restrictions for practicing? Time, duration, ...', max_length=180, verbose_name='practice notes'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('n', 'Non-Binary'), ('x', "Don't know")], max_length=5, verbose_name='preferred gender'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='provides_breakfast',
            field=models.BooleanField(verbose_name='breakfast'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='provides_transport',
            field=models.BooleanField(help_text='do you provide transport for the contestants?', verbose_name='transport'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='single_rooms',
            field=models.PositiveSmallIntegerField(verbose_name='no of single rooms'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='smoking_allowed',
            field=models.BooleanField(verbose_name='smokers allowed'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submitted'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='surname',
            field=models.CharField(max_length=120, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='education',
            field=models.TextField(max_length=500, verbose_name='artistic CV'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='notes',
            field=models.TextField(blank=True, help_text='any information that we should know beforehand, not mentioned otherwise in this form', verbose_name='notes'),
        ),
    ]
