# Generated by Django 4.0.4 on 2022-10-12 13:09

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_auto_20200830_1851'),
        ('tmc', '0007_remove_hostfamily_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=120, verbose_name='given name')),
                ('surname', models.CharField(max_length=120, verbose_name='surname')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='please remember to add your country prefix', max_length=128, region=None, verbose_name='phone')),
                ('email', models.EmailField(error_messages={'unique': 'This email has already been registered.'}, help_text='make sure your e-mail is correct, as all communication will be done over e-mail', max_length=254, unique=True, verbose_name='e-mail')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted')),
                ('other_ressorts', models.CharField(blank=True, max_length=200)),
                ('is_spontaneous', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='address')),
                ('languages', models.ManyToManyField(to='tmc.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ressort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='jurymember',
            name='ahv_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='bic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='city_of_departure',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='date_of_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='date_of_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='iban',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='location_of_arrival',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='location_of_departure',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='means_of_travel',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='notes_tranpsort',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='payee',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='terminal_of_arrival',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='terminal_of_departure',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='transport_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='transport_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('whole_day', 'Whole Day')], max_length=60)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.dateslot')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.helper')),
            ],
        ),
        migrations.AddField(
            model_name='helper',
            name='ressorts',
            field=models.ManyToManyField(to='tmc.ressort'),
        ),
        migrations.AddField(
            model_name='helper',
            name='slots',
            field=models.ManyToManyField(through='tmc.TimeSlot', to='tmc.dateslot'),
        ),
        migrations.AddField(
            model_name='helper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
