# Generated by Django 4.0.4 on 2022-10-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0008_dateslot_helper_ressort_jurymember_ahv_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurymember',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='jurymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='is_pre',
            field=models.BooleanField(default=True),
        ),
    ]
