# Generated by Django 4.0.4 on 2022-10-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0009_remove_jurymember_birthdate_jurymember_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='has_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscription',
            name='has_recordings',
            field=models.BooleanField(default=False),
        ),
    ]
