# Generated by Django 4.0.4 on 2022-10-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0010_inscription_has_documents_inscription_has_recordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurymember',
            name='city_of_departure',
        ),
        migrations.AddField(
            model_name='helper',
            name='other_languages',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
