# Generated by Django 4.0.4 on 2022-10-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0011_remove_jurymember_city_of_departure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurymember',
            name='is_pre',
        ),
        migrations.AddField(
            model_name='jurymember',
            name='kind',
            field=models.CharField(blank=True, max_length=120, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='is_spontaneous',
            field=models.BooleanField(help_text='are you available spontaneously', verbose_name='spontaneous?'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='languages',
            field=models.ManyToManyField(to='tmc.language', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='other_languages',
            field=models.CharField(blank=True, max_length=120, verbose_name='other languages'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='other_ressorts',
            field=models.CharField(blank=True, max_length=200, verbose_name='other ressorts'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='ressorts',
            field=models.ManyToManyField(to='tmc.ressort', verbose_name='ressorts'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='slots',
            field=models.ManyToManyField(through='tmc.TimeSlot', to='tmc.dateslot', verbose_name='slots'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='double_rooms',
            field=models.PositiveSmallIntegerField(help_text='how many rooms for two people can you provide? Below you can attach notes if necessary.', verbose_name='no of double rooms'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='has_own_bathroom',
            field=models.BooleanField(help_text='do guests have their own bathroom?', verbose_name='own bathroom'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='has_wifi',
            field=models.BooleanField(help_text='can guests use your wifi?', verbose_name='wifi'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='languages',
            field=models.ManyToManyField(help_text='what languages do you speak?', to='tmc.language', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('n', 'Non-Binary')], max_length=5, verbose_name='preferred gender'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='provides_breakfast',
            field=models.BooleanField(help_text='can you provide breakfast?', verbose_name='breakfast provided'),
        ),
        migrations.AlterField(
            model_name='hostfamily',
            name='single_rooms',
            field=models.PositiveSmallIntegerField(help_text='how many single rooms can you provide?', verbose_name='no of single rooms'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='ahv_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ahv number'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='bic',
            field=models.CharField(blank=True, max_length=20, verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='date_of_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of arrival'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='date_of_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of departure'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='iban',
            field=models.CharField(blank=True, max_length=35, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.instrument', verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='location_of_arrival',
            field=models.CharField(blank=True, max_length=130, verbose_name='location of arrival'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='location_of_departure',
            field=models.CharField(blank=True, max_length=130, verbose_name='location of departure'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='means_of_travel',
            field=models.CharField(blank=True, max_length=120, verbose_name='means of travel'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='notes_tranpsort',
            field=models.TextField(blank=True, verbose_name='notes on transport'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='payee',
            field=models.CharField(blank=True, help_text='name of the person receiving the payment', max_length=120, verbose_name='payee'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='terminal_of_arrival',
            field=models.CharField(blank=True, max_length=130, verbose_name='terminal of arrival'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='terminal_of_departure',
            field=models.CharField(blank=True, max_length=130, verbose_name='terminal of departuree'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='transport_arrival',
            field=models.BooleanField(default=False, help_text='do you need transport on arrival?', verbose_name='need transport on arrival'),
        ),
        migrations.AlterField(
            model_name='jurymember',
            name='transport_departure',
            field=models.BooleanField(default=False, verbose_name='need transport on departure'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.dateslot', verbose_name='datum'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('whole_day', 'Whole Day')], max_length=60, verbose_name='slot'),
        ),
    ]
