# Generated by Django 4.0.4 on 2022-10-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0012_remove_jurymember_is_pre_jurymember_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurymember',
            name='bank_info',
            field=models.CharField(blank=True, max_length=280, verbose_name='bank info'),
        ),
    ]
