# Generated by Django 4.1.3 on 2022-12-16 14:07

import django.core.validators
from django.db import migrations, models
import tmc.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0016_alter_inscription_secret_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='is_qualified',
            field=models.BooleanField(default=False, verbose_name='qualified'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording',
            field=models.FileField(upload_to=tmc.models.recording_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'm4v'])]),
        ),
    ]
