# Generated by Django 4.1.3 on 2022-12-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0017_inscription_is_qualified_alter_recording_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_of_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inscription',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
