# Generated by Django 4.1.3 on 2023-01-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0018_inscription_date_of_arrival_inscription_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1)),
                ('excludes', models.ManyToManyField(blank=True, to='tmc.piece')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('required', models.FloatField(default=1)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.round')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.inscription')),
                ('pieces', models.ManyToManyField(to='tmc.piece')),
                ('set_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.setlist')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='set_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmc.setlist'),
        ),
    ]
