# Generated by Django 4.1.3 on 2023-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0020_piece_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={'ordering': ['set_list']},
        ),
        migrations.AlterModelOptions(
            name='setlist',
            options={'ordering': ['round__name', 'name']},
        ),
        migrations.AddField(
            model_name='inscription',
            name='time_of_arrival',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
