# Generated by Django 4.1.7 on 2025-07-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0021_alter_selection_options_alter_setlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='food_needed',
        ),
    ]
