# Generated by Django 4.1.7 on 2025-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc', '0022_remove_inscription_food_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurymember',
            name='insurance_documents',
            field=models.FileField(blank=True, upload_to='documents-jury/'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos-jury/'),
        ),
    ]
